### ISSUE TITLE
This extension violates the Chrome Web Store policy. 

### ISSUE THREAD

**Issue by jritza** [umarsheikh13/recent-history#14]
This extension was removed from Chrome web store. Any chance of bringing it back up? The web store page is now inaccessible.  I have used this extension for years so it's sad to see it go.

**Comment by umarsheikh13** [comment]
Hiya. Chrome have introduced some compulsory privacy policy fields that have to be filled in for it to remain in the web store. I've filled everything in and submitted it for review and now just waiting for them to approve it.
